version: '3'
services:
  spring:
    build:
      context: ./B206-spring-repo
      dockerfile: Dockerfile
    container_name: spring-container
    ports:
      - "8080:80"
    networks:
      - B206-networks
    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      - MYSQL_ROOT_PASSWORD=ssafy
      - MYSQL_DATABASE=lam
      - MYSQL_USER=ssafy
      - MYSQL_PASSWORD=ssafy
    ports:
      - "3306:3306"
    networks:
      - B206-networks
networks:
  B206-networks: {}

